import json
import numpy as np
import pandas as pd
from src.matching.features import build_pair_features
from src.matching.train import train_classifier

def load_data():
    """
    Load cleaned datasets from Member 1 and the split candidate pairs/labels.
    Adjust file paths and column names to match your project's data files.
    """
    print("Loading datasets...")
    # 1. Load cleaned records from Member 1
    s1_df = pd.read_csv("data/source1_clean.csv")
    s23_df = pd.read_csv("data/source23_clean.csv")

    # Convert DataFrames to dictionaries keyed by 'entity_id' for fast lookup
    s1_dict = s1_df.set_index("entity_id").to_dict("index")
    s23_dict = s23_df.set_index("entity_id").to_dict("index")

    # 2. Load candidate pairs (e.g., JSON generated by Member 1)
    # Format expected: {"s1_id_1": ["cand_id_1", "cand_id_2"], ...}
    with open("data/candidate_pairs_train.json", "r", encoding="utf-8") as f:
        candidates_train = json.load(f)

    with open("data/candidate_pairs_val.json", "r", encoding="utf-8") as f:
        candidates_val = json.load(f)

    # 3. Load ground truth labels
    # Expected CSV structure: source1_entity_id, candidate_entity_id, label (1 or 0)
    train_labels_df = pd.read_csv("data/train_labels.csv")
    val_labels_df = pd.read_csv("data/val_labels.csv")

    return s1_dict, s23_dict, candidates_train, candidates_val, train_labels_df, val_labels_df

def main():
    # Load actual datasets
    s1_records, s23_records, candidates_train, candidates_val, train_labels_df, val_labels_df = load_data()

    # Build features for Train set
    print("Building training pair features...")
    X_train_df = build_pair_features(s1_records, s23_records, candidates_train)
    
    # Align labels with the exact order of pairs in X_train_df
    train_merged = X_train_df[["source1_entity_id", "candidate_entity_id"]].merge(
        train_labels_df, on=["source1_entity_id", "candidate_entity_id"], how="left"
    )
    y_train = train_merged["label"].fillna(0).astype(int).values

    # Build features for Validation set
    print("Building validation pair features...")
    X_val_df = build_pair_features(s1_records, s23_records, candidates_val)

    # Align labels for validation set
    val_merged = X_val_df[["source1_entity_id", "candidate_entity_id"]].merge(
        val_labels_df, on=["source1_entity_id", "candidate_entity_id"], how="left"
    )
    y_val = val_merged["label"].fillna(0).astype(int).values

    # Drop ID columns before training LightGBM
    id_cols = ["source1_entity_id", "candidate_entity_id"]
    X_train_features = X_train_df.drop(columns=id_cols)
    X_val_features = X_val_df.drop(columns=id_cols)

    # Train classifier and find optimal threshold
    print("Training LightGBM model...")
    model, best_threshold = train_classifier(X_train_features, y_train, X_val_features, y_val)

    # Save model checkpoint for run_pipeline.py
    model.save_model("output/lgbm_matching_model.txt")
    print(f"Model saved to output/lgbm_matching_model.txt with best threshold: {best_threshold:.2f}")

if __name__ == "__main__":
    main()